name: berflow

services:
  berflow:
    image: ghcr.io/klarak777/b-rflow:latest
    container_name: berflow-app
    restart: unless-stopped
    ports:
      - "3100:3000"
    mem_limit: 300m
    networks:
      - berflow-net

networks:
  berflow-net:
    name: berflow-net
